synapse:
  grs: 
    id: syn24184523
    name: Global_Response_Set
    type: file
    description: BPC REDCap mapping between coded and uncoded values to supplement data dictionaries
  prissmm: 
    id: syn22684834
    name: PRISSMM Documentation Versions
    type: table
    description: PRISSMM formatted data dictionaries for REDCap
  rca_files: 
    id: syn23286928
    name: curated
    type: folder
    description: REDCap academic formatted files of merged BPC data ready for import to Synapse tables
upload:
  BrCa:
    DFCI:
      data1: syn26160187
      header1: syn25981842
      data2: syn26160184
      header2: syn25981841
    MSK:
      data1: syn24202045
    VICC:
      data1: syn24201984
  CRC:
    DFCI:
      data1: syn25961098
      header1: syn25961099
    MSK:
      data1: syn25953196
    VICC:
      data1: syn25961124
  NSCLC:
    DFCI:
      data1: syn25582436
      header1: syn25582427
    MSK:
      data1: syn25557012
    UHN:
      data1: syn25686838
    VICC:
      data1: syn25579921
  PANC:
    DFCI:
      data1: syn25544638
      header1: syn25544639
    MSK:
      data1: syn25541828
    UHN:
      data1: syn26033209
    VICC:
      data1: syn25541702
  Prostate:
    DFCI:
      data1: syn26230815
      header1: syn25592217
    MSK:
      data1: syn26230493
    UHN:
      data1: syn26212729
    VICC:
      data1: syn26231094
  BLADDER:
    DFCI:
      data1: syn26250078
      header1: syn26250090
    MSK:
      data1: syn26250083
    UHN:
      data1: syn26250084
    VICC:
      data1: syn26250085
column_name:
  variable_name: "Variable / Field Name"
  form_name: "Form Name"
  field_type: "Field Type"
  variable_mapping: "Choices, Calculations, OR Slider Labels"
  variable_type: "Text Validation Type OR Show Slider Number"
  variable_min: "Text Validation Min"
  variable_max: "Text Validation Max"
  rs_label: "Response Set Label"
  rs_value: "Response Set Values"
mapping:
  complete:
    0: "Not Started"
    1: "Data Entry Started"
    2: "Completed"
    5: "Monitoring Complete"
    6: "Form Removed"
    7: "Form Locked"
    8: "Form Signed"
  yesno_rca:
    0: "No"
    1: "Yes"
  instrument:
    ca_directed_drugs: "Ca Directed Drugs"
    cancer_diagnosis: "Cancer Diagnosis"
    cancer_panel_test: "Cancer Panel Test"
    prissmm_imaging: "Prissmm Imaging"
    prissmm_med_onc_assessment: "Prissmm Med Onc Assessment"
    prissmm_pathology: "Prissmm Pathology"
    prissmm_tumor_marker: "Prissmm Tumor Marker"
    ca_directed_radtx: "Ca Directed Radtx"
misc:
  all: all
