synapse:
  grs: 
    id: syn24184523
    name: Global_Response_Set
    type: file
    description: BPC REDCap mapping between coded and uncoded values to supplement data dictionaries
  prissmm: 
    id: syn22684834
    name: PRISSMM Documentation Versions
    type: table
    description: PRISSMM formatted data dictionaries for REDCap
  rca_files: 
    id: syn23286928
    name: curated
    type: folder
    description: REDCap academic formatted files of merged BPC data ready for import to Synapse tables
upload:
  BrCa:
    DFCI:
      data1: syn26160187
      #header1: syn25981842
      #data2: syn26160184
      #header2: syn25981841
    MSK:
      data1: syn24202045
    VICC:
      data1: syn24201984
  CRC:
    DFCI:
      data1: syn25961098
      #header1: syn25961099
    MSK:
      data1: syn25953196
    VICC:
      data1: syn25961124
  NSCLC:
    DFCI:
      data1: syn25582436
      #header1: syn25582427
    MSK:
      data1: syn25557012
    UHN:
      data1: syn25686838
    VICC:
      data1: syn25579921
  PANC:
    DFCI:
      data1: syn25544638
      header1: syn25544639
    MSK:
      data1: syn25541828
    UHN:
      data1: syn26033209
    VICC:
      data1: syn25541702
  Prostate:
    DFCI:
      data1: syn26230815
      header1: syn25592217
    MSK:
      data1: syn26230493
    UHN:
      data1: syn26212729
    VICC:
      data1: syn26231094
  BLADDER:
    DFCI:
      data1: syn26250078
      header1: syn26250090
    MSK:
      data1: syn26250083
    UHN:
      data1: syn26250084
    VICC:
      data1: syn26250085
  NSCLC2:
    DFCI:
      data1: syn27351603
    # DUKE:
      # data1: syn30821503
    MSK:
      data1: syn27351615
    # PROV:
      # data1: syn30821505
    # UCSF:
      # data1: syn30821507
    UHN:
      data1: syn27351619
    # VICC:
      # data1: syn27351623
  CRC2:
    DFCI:
      data1: syn29418170
      # data2: syn52623830
    DUKE:
      data1: syn30821496
    MSK:
      data1: syn29418172
    PROV:
      data1: syn30821498
    UCSF:
      data1: syn30821500
    UHN:
      data1: syn29418174
    VICC:
      data1: syn29418176
  RENAL:
    DFCI:
      data1: syn29418122
    DUKE:
      data1: syn30821482
    MSK:
      data1: syn29418128
    PROV:
      data1: syn30821484
    UCSF:
      data1: syn30821486
    UHN:
      data1: syn29418131
    VICC:
      data1: syn29418134
  MELANOMA:
    DFCI:
      data1: syn29418138
    MSK:
      data1: syn29418140
    PROV:
      data1: syn30821491
    UCSF:
      data1: syn30821493
    UHN:
      data1: syn29418143
    VICC:
      data1: syn29418146
  OVARIAN:
    DFCI:
      data1: syn29418091
    DUKE:
      data1: syn30821466
    MSK:
      data1: syn29418095
    PROV:
      data1: syn30821470
    UCSF:
      data1: syn30821472
    UHN:
      data1: syn29418098
    VICC:
      data1: syn29418100
  ESOPHAGO:
    DFCI:
      data1: syn29418106
    DUKE:
      data1: syn30821475
    MSK:
      data1: syn29418110
    PROV:
      data1: syn30821477
    UCSF:
      data1: syn30821479
    UHN:
      data1: syn29418113
    VICC:
      data1: syn29418117
column_name:
  variable_name: "Variable / Field Name"
  form_name: "Form Name"
  field_type: "Field Type"
  variable_mapping: "Choices, Calculations, OR Slider Labels"
  variable_type: "Text Validation Type OR Show Slider Number"
  variable_min: "Text Validation Min"
  variable_max: "Text Validation Max"
mapping:
  complete:
    0: "Not Started"
    1: "Data Entry Started"
    2: "Completed"
    5: "Monitoring Complete"
    6: "Form Removed"
    7: "Form Locked"
    8: "Form Signed"
  instrument:
    ca_directed_drugs: "Ca Directed Drugs"
    cancer_diagnosis: "Cancer Diagnosis"
    cancer_panel_test: "Cancer Panel Test"
    prissmm_imaging: "Prissmm Imaging"
    prissmm_med_onc_assessment: "Prissmm Med Onc Assessment"
    prissmm_pathology: "Prissmm Pathology"
    prissmm_tumor_marker: "Prissmm Tumor Marker"
    ca_directed_radtx: "Ca Directed Radtx"
misc:
  all: all
