---
synapse:
  main_patient: 
    id: syn7517669
    name: Patient Clinical Database
    type: table
    description: main GENIE table of all patients with patient info
  main_sample: 
    id: syn7517674
    name: Sample Clinical Database
    type: table
    description: main GENIE table of all samples with sample info
  bpc_patient:
    id: syn21446700
    name: Patient Characteristics
    type: table
    description: consolidated BPC patient characteristics info
  bpc_sample:
    id: syn21446709
    name: Cancer Panel Test
    type: table
    description: BPC sample table
  selection:
    id: syn26228746
    name: Case Selection Counts
    type: table
    description: reference table of case selection counts for GENIE BPC cohorts
  ids:
    id: syn20781633
    name: IDs for export request
    type: folder
    description: folder holding IDs for case selection by cohort and site
  bpc_internal:
    id: syn21435590
    name: GENIE BioPharma Collaborative Internal
    type: project
    description: BPC internal project space
  bpc_removal_patient:
    id: syn25998970
    name: BPC Patient Retraction
    type: table
    description: patients removed from BPC for quality or other reasons
  bpc_removal_sample:
    id: syn25779833
    name: BPC Sample Retraction
    type: table
    description: samples removed from BPC for quality or other reasons
  case_selection:
    id: syn26228746
    name: Case Selection Counts
    type: table
    description: Case selection counts reference table in BPC Internal project
  selection_criteria:
    id: syn31003441
    name: Case Selection Criteria
    type: table
    description: Case selection criteria reference table in BPC Internal project
default:
  global:
    age_min: 18
    age_max: Inf
    sdv: 0.2
    irr: 0.05
  site:
    CHOP:
      pressure: 10
      seed: 44342
    COLU:
      pressure: 10
      seed: 342
    CRUK:
      pressure: 10
      seed: 23425
    DFCI: 
      pressure: 15
      seed: 58029
    DUKE:
      pressure: 10
      seed: 37383
    GRCC:
      pressure: 10
      seed: 943321
    JHU:
      pressure: 10
      seed: 83782
    MSK:
      pressure: 15
      seed: 7
    PROV:
      pressure: 10
      seed: 88830
    UCHI:
      pressure: 10
      seed: 717112
    UCSF:
      pressure: 10
      seed: 65379
    UHN: 
      pressure: 10
      seed: 123456
    VICC:
      pressure: 10
      seed: 992
    VHIO:
      pressure: 10
      seed: 5509
phase:
  1:
    cohort: 
      BLADDER:
        name: BLADDER
        site:
          DFCI:
            production: 320
            adjusted: 320
          MSK:
            production: 320
            adjusted: 320
          UHN:
            production: 45
            adjusted: 47
            pressure: 3
            sdv: 9
            irr: 3
          VICC:
            production: 66
            adjusted: 62
            pressure: 10
        date:
          seq_min: Jan-2013
          seq_max: Dec-2018
        oncotree:
          root: BLADDER
          allowed_codes: 
            - BLCA
            - UTUC
            - BLAD
            - SCBC
            - BLSC
      BrCa:
        name: BrCa
        site:
          DFCI:
            production: 428
            adjusted: 428
          MSK:
            production: 529
            adjusted: 529
          UHN:
            production: 0
            adjusted: 0
          VICC:
            production: 169
            adjusted: 173
            pressure: 15
        date:
          seq_min: Jan-2013
          seq_max: Apr-2018
        age_max: 56
        oncotree:
          root: BREAST
          allowed_codes: 
            - BRCA
            - BRCANOS
            - BRCNOS
            - IDC
            - ILC
            - MDLC
            - BA
            - MPT
            - MBC
            - MMBC
            - MSCC
      CRC:
        name: CRC
        site:
          DFCI:
            production: 570
            adjusted: 570
          MSK:
            production: 705
            adjusted: 705
          UHN:
            production: 0
            adjusted: 0
          VICC:
            production: 225
            adjusted: 226
        date:
          seq_min: Jan-2015
          seq_max: Apr-2018
        oncotree:
          root: COADREAD
          allowed_codes: 
            - COADREAD
            - COAD
            - MACR
            - SRCCR
            - READ
      NSCLC:
        name: NSCLC
        site:
          DFCI:
            production: 713
            adjusted: 710
          MSK:
            production: 881
            adjusted: 881
          UHN:
            production: 55
            adjusted: 55
            pressure: 0
            sdv: 6
            irr: 3
            seq_min: Jan-2014
          VICC:
            production: 226
            adjusted: 227
        date:
          seq_min: Jan-2015
          seq_max: Dec-2017
        oncotree:
          root: NSCLC
          allowed_codes: 
            - NSCLC
            - CMPT
            - LCLC
            - LUAD
            - LUPC
            - LUSC
            - NSCLCPD
            - LUAS
            - LUMEC
            - LECLC
            - CCLC
            - RLCLC
            - GCLC
            - BLCLC
      PANC:
        name: PANC
        site:
          DFCI:
            production: 444
            adjusted: 444
          MSK:
            production: 545
            adjusted: 545
          UHN:
            production: 70
            adjusted: 70
            sdv: 14
            irr: 4
          VICC:
            production: 65
            adjusted: 64
        date:
          seq_min: Jan-2013
          seq_max: Dec-2018
        oncotree:
          root: PANCREAS
          allowed_codes: 
            - PAAD
            - PAASC
            - PAAC
            - UCP
      Prostate:
        name: Prostate
        site:
          DFCI:
            production: 467
            adjusted: 467
          MSK:
            production: 568
            adjusted: 568
          UHN:
            production: 60
            adjusted: 60
            pressure: 3
            sdv: 12
            irr: 3
          VICC:
            production: 30
            adjusted: 30
        date:
          seq_min: Jan-2013
          seq_max: Dec-2018
        oncotree:
          root: PROSTATE
          allowed_codes: 
            - PRAD
  1_additional: 
    cohort:
      NSCLC:
          name: NSCLC
          date:
            seq_min: Jan-2018
            seq_max: Sep-2021
          oncotree:
            root: NSCLC
            allowed_codes: 
              - NSCLC
              - CMPT
              - LCLC
              - LUAD
              - LUPC
              - LUSC
              - NSCLCPD
              - LUAS
              - LUMEC
              - LECLC
              - CCLC
              - RLCLC
              - GCLC
              - BLCLC
  2:
    cohort: 
      NSCLC:
        name: NSCLC
        site:
          CHOP:
            production: 0
            adjusted: 0
          COLU:
            production: 410
            adjusted: 410
          CRUK:
            production: 0
            adjusted: 0
          DFCI:
            production: 410
            adjusted: 410
          DUKE:
            production: 210
            adjusted: 210
            date:
              seq_min: Jul-2017
              seq_max: Dec-2019
          GRCC:
            production: 102
            adjusted: 102
          JHU:
            production: 462
            adjusted: 462
          MSK:
            production: 615
            adjusted: 615
          PROV:
            production: 210
            adjusted: 210
          UCHI:
            production: 0
            adjusted: 0
          UCSF:
            production: 100
            adjusted: 100
            date:
              seq_min: Oct-2016
              seq_max: Dec-2019
          UHN:
            production: 35
            adjusted: 35
            date: 
              seq_min: Jan-2017
              seq_max: Dec-2019
          VICC:
            production: 210
            adjusted: 210
          VHIO:
            production: 51
            adjusted: 51
        date: 
          seq_min: Jan-2018
          seq_max: Dec-2019
        oncotree:
          root: NSCLC
          allowed_codes: 
            - CMPT
            - SPCC
            - SGTTL
            - NUTCL
            - LCLC
            - LUAD
            - LUPC
            - LUSC
            - NSCLCPD
            - LUAS
            - LUMEC
            - GCLC
            - LUACC
            - NSCLC
      CRC:
        name: CRC
        site: 
          DFCI:
            production: 300
            adjusted: 300
          DUKE:
            production: 135
            adjusted: 135
          MSK:
            production: 500
            adjusted: 500
          PROV:
            production: 135
            adjusted: 135
          UCSF:
            production: 60
            adjusted: 60
          UHN:
            production: 110
            adjusted: 110
            date:
              seq_min: Jul-2017
              seq_max: Dec-2020
          VICC:
            production: 135
            adjusted: 135
            date: 
              seq_min: Apr-2014
              seq_max: Dec-2020
        date: 
          seq_min: Jan-2018
          seq_max: Dec-2020
        oncotree:
          root: BOWEL
          allowed_codes: 
            - COAD
            - COADREAD
            - READ
            - MACR
            - SRCCR
      RENAL:
        name: RENAL
        site: 
          DFCI:
            production: 400
            adjusted: 400
          DUKE:
            production: 30
            adjusted: 30
          MSK:
            production: 600
            adjusted: 600
          PROV:
            production: 45
            adjusted: 45
          UCSF:
            production: 46
            adjusted: 46
          UHN:
            production: 40
            adjusted: 40
          VICC:
            production: 56
            adjusted: 56
        date: 
          seq_min: Apr-2012
          seq_max: Jun-2020
        oncotree:
          root: RCC
          allowed_codes: 
            - CCRCC
            - RCC
            - PRCC
            - NCCRCC
            - SCCRCC
            - CCPRC
      OVARIAN:
        name: OVARIAN
        site: 
          DFCI:
            production: 300
            adjusted: 300
          DUKE:
            production: 80
            adjusted: 80
          MSK:
            production: 500
            adjusted: 500
          PROV:
            production: 65
            adjusted: 65
          UCSF:
            production: 80
            adjusted: 80
          UHN:
            production: 80
            adjusted: 80
          VICC:
            production: 75
            adjusted: 75
        date: 
          seq_min: Jan-2014
          seq_max: Dec-2020
        oncotree:
          root: OVARY
          allowed_codes: 
            - HGSOC
            - SOC
            - CCOV
            - EOV
            - HGSFT
            - OVT
            - LGSOC
      MELANOMA:
        name: MELANOMA
        site: 
          DFCI:
            production: 300
            adjusted: 300
          DUKE:
            production: 0
            adjusted: 0
          MSK:
            production: 500
            adjusted: 500
          PROV:
            production: 103
            adjusted: 103
          UCSF:
            production: 103
            adjusted: 103
          UHN:
            production: 40
            adjusted: 40
          VICC:
            production: 103
            adjusted: 103
        date: 
          seq_min: Oct-2017
          seq_max: Jun-2021
        oncotree:
          root: MEL
          allowed_codes: 
            - SKCM
            - MEL
      ESOPHAGO:
        name: ESOPHAGO
        site:
          CHOP:
            production: 0
            adjusted: 0
          COLU:
            production: 50
            adjusted: 50
          CRUK:
            production: 0
            adjusted: 0
          DFCI:
            production: 315
            adjusted: 315
          DUKE:
            production: 90
            adjusted: 90
          GRCC:
            production: 52
            adjusted: 52
          JHU:
            production: 31
            adjusted: 31
          MSK:
            production: 515
            adjusted: 515
          PROV:
            production: 60
            adjusted: 60
          UCHI:
            production: 1
            adjusted: 1
            pressure: 0
          UCSF:
            production: 45
            adjusted: 45
          UHN:
            production: 100
            adjusted: 100
          VHIO:
            production: 90
            adjusted: 90
          VICC:
            production: 79
            adjusted: 79
        date: 
          seq_min: Apr-2012
          seq_max: Dec-2021
        oncotree:
          root: EGC
          allowed_codes: 
            - ESCA
            - STAD
            - GEJ
            - EGC
            - SPDAC
            - SSRCC
            - ESCC
            - EPDCA
            - DSTAD
            - ISTAD
            - TSTAD
            - MSTAD
            - USTAD
            - PSTAD
            - GRC
release:
  cohort:
    BLADDER: 
      patient_level_dataset: NA
    BrCa: 
      patient_level_dataset: syn26253365
    CRC:
      patient_level_dataset: syn26046793
    ESOPHAGO:
      patient_level_dataset: NA
    MELANOMA:
      patient_level_dataset: NA
    NSCLC:
      patient_level_dataset: syn25985884
    OVARIAN:
      patient_level_dataset: NA
    PANC:
      patient_level_dataset: NA
    Prostate:
      patient_level_dataset: NA
    RENAL:
      patient_level_dataset: NA
misc:
  debug: TRUE
