name: Build and Push Docker Images

on:
  push:
    branches: [develop, 'GEN*', 'gen*']
    paths:
      - 'scripts/references/**'
      - '.github/workflows/build-docker-images.yml'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io

    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set Tag Based on Branch
      id: tags
      run: echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV

    - name: Determine Image to Build
      id: image
      run: |
        if git diff --name-only HEAD~ -- | grep -q '^scripts/references/'; then
          echo "IMAGE_NAME=${{ github.repository }}-references" >> $GITHUB_ENV
          echo "DOCKERFILE_PATH=scripts/references/Dockerfile" >> $GITHUB_ENV
        else
          echo "IMAGE_NAME=" >> $GITHUB_ENV  # No image to build
        fi

    - name: Skip Build if No Image Determined
      if: env.IMAGE_NAME == ''
      run: echo "No changes in targeted directories; skipping Docker build and push."

    - name: Log in to GHCR
      if: env.IMAGE_NAME != ''
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      if: env.IMAGE_NAME != ''
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} -f ${{ env.DOCKERFILE_PATH }} .
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
